/* Generated by scripts/buildRussianHintWorker.mjs. */
const modules={"./cardService":function(require,module,exports){
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.RANK_VALUE = exports.SUITS = exports.RANKS = void 0;
exports.createDeck = createDeck;
exports.shuffleDeck = shuffleDeck;
exports.rankToLabel = rankToLabel;
exports.suitToSymbol = suitToSymbol;
exports.isRedSuit = isRedSuit;
exports.RANKS = ['2', '3', '4', '5', '6', '7', '8', '9', 'T', 'J', 'Q', 'K', 'A'];
exports.SUITS = ['hearts', 'diamonds', 'clubs', 'spades'];
exports.RANK_VALUE = {
    '2': 2,
    '3': 3,
    '4': 4,
    '5': 5,
    '6': 6,
    '7': 7,
    '8': 8,
    '9': 9,
    T: 10,
    J: 11,
    Q: 12,
    K: 13,
    A: 14,
};
function createDeck() {
    const deck = [];
    for (const suit of exports.SUITS) {
        for (const rank of exports.RANKS) {
            deck.push({ id: `${rank}-${suit}`, rank, suit });
        }
    }
    return deck;
}
function shuffleDeck(deck) {
    const shuffled = [...deck];
    for (let i = shuffled.length - 1; i > 0; i--) {
        const j = Math.floor(Math.random() * (i + 1));
        [shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]];
    }
    return shuffled;
}
function rankToLabel(rank) {
    return rank === 'T' ? '10' : String(rank);
}
function suitToSymbol(suit) {
    switch (suit) {
        case 'hearts':
            return '♥';
        case 'diamonds':
            return '♦';
        case 'clubs':
            return '♣';
        case 'spades':
            return '♠';
        default:
            return String(suit);
    }
}
function isRedSuit(suit) {
    return suit === 'hearts' || suit === 'diamonds';
}

},
"./handEvaluator":function(require,module,exports){
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.scoreRank = scoreRank;
exports.scoreFirstValue = scoreFirstValue;
exports.evaluateCardScore = evaluateCardScore;
exports.scoreHandResult = scoreHandResult;
exports.getProHintCacheKey = getProHintCacheKey;
exports.getProHint = getProHint;
exports.evaluateBestHand = evaluateBestHand;
exports.compareHands = compareHands;
exports.dealerQualifies = dealerQualifies;
exports.getAntePayout = getAntePayout;
const cardService_1 = require("./cardService");
const HAND_NAMES = {
    8: { en: 'Straight Flush', ru: 'Стрит-флеш' },
    7: { en: 'Four of a Kind', ru: 'Каре' },
    6: { en: 'Full House', ru: 'Фулл-хаус' },
    5: { en: 'Flush', ru: 'Флеш' },
    4: { en: 'Straight', ru: 'Стрит' },
    3: { en: 'Three of a Kind', ru: 'Тройка' },
    2: { en: 'Two Pair', ru: 'Две пары' },
    1: { en: 'Pair', ru: 'Пара' },
    0: { en: 'High Card', ru: 'Старшая карта' },
};
function combinations(arr, size) {
    const result = [];
    const combo = [];
    function walk(start) {
        if (combo.length === size) {
            result.push([...combo]);
            return;
        }
        for (let i = start; i <= arr.length - (size - combo.length); i++) {
            combo.push(arr[i]);
            walk(i + 1);
            combo.pop();
        }
    }
    walk(0);
    return result;
}
const SUIT_INDEX = {
    hearts: 0,
    diamonds: 1,
    clubs: 2,
    spades: 3,
};
const STRAIGHT_MASKS = [
    { high: 14, mask: (1 << 14) | (1 << 13) | (1 << 12) | (1 << 11) | (1 << 10) },
    { high: 13, mask: (1 << 13) | (1 << 12) | (1 << 11) | (1 << 10) | (1 << 9) },
    { high: 12, mask: (1 << 12) | (1 << 11) | (1 << 10) | (1 << 9) | (1 << 8) },
    { high: 11, mask: (1 << 11) | (1 << 10) | (1 << 9) | (1 << 8) | (1 << 7) },
    { high: 10, mask: (1 << 10) | (1 << 9) | (1 << 8) | (1 << 7) | (1 << 6) },
    { high: 9, mask: (1 << 9) | (1 << 8) | (1 << 7) | (1 << 6) | (1 << 5) },
    { high: 8, mask: (1 << 8) | (1 << 7) | (1 << 6) | (1 << 5) | (1 << 4) },
    { high: 7, mask: (1 << 7) | (1 << 6) | (1 << 5) | (1 << 4) | (1 << 3) },
    { high: 6, mask: (1 << 6) | (1 << 5) | (1 << 4) | (1 << 3) | (1 << 2) },
    { high: 5, mask: (1 << 14) | (1 << 5) | (1 << 4) | (1 << 3) | (1 << 2) },
];
function straightHighFromMask(mask) {
    for (const straight of STRAIGHT_MASKS) {
        if ((mask & straight.mask) === straight.mask)
            return straight.high;
    }
    return null;
}
function addHighestRanks(values, rankMask, count, excludeOne = 0, excludeTwo = 0) {
    for (let value = 14; value >= 2 && values.length < count; value--) {
        if (value !== excludeOne && value !== excludeTwo && (rankMask & (1 << value)) !== 0) {
            values.push(value);
        }
    }
}
function pickCardsByRank(rankCards, ranks) {
    const picked = [];
    for (const rank of ranks) {
        const cardsForRank = rankCards[rank];
        for (let i = 0; i < cardsForRank.length; i++) {
            picked.push(cardsForRank[i]);
        }
    }
    return picked.slice(0, 5);
}
function pickCardsForRepeatedRanks(rankCards, repeatedRanks, kickerRanks = []) {
    const picked = [];
    for (const repeated of repeatedRanks) {
        const cardsForRank = rankCards[repeated.rank];
        for (let i = 0; i < repeated.count; i++) {
            picked.push(cardsForRank[i]);
        }
    }
    for (const rank of kickerRanks) {
        const cardsForRank = rankCards[rank];
        if (cardsForRank[0])
            picked.push(cardsForRank[0]);
    }
    return picked;
}
const SCORE_V0 = 15 ** 4;
const SCORE_RANK = 15 ** 5;
const SCORE_RANK_COUNTS = new Array(15).fill(0);
const SCORE_SUIT_COUNTS = [0, 0, 0, 0];
const SCORE_SUIT_MASKS = [0, 0, 0, 0];
function makeScore(rank, v0 = 0, v1 = 0, v2 = 0, v3 = 0, v4 = 0) {
    return rank * SCORE_RANK + v0 * SCORE_V0 + v1 * 15 ** 3 + v2 * 15 ** 2 + v3 * 15 + v4;
}
function scoreRank(score) {
    return Math.floor(score / SCORE_RANK);
}
function scoreFirstValue(score) {
    return Math.floor((score % SCORE_RANK) / SCORE_V0);
}
function nthHighestRank(rankMask, nth, excludeOne = 0, excludeTwo = 0) {
    let seen = 0;
    for (let value = 14; value >= 2; value--) {
        if (value !== excludeOne && value !== excludeTwo && (rankMask & (1 << value)) !== 0) {
            seen++;
            if (seen === nth)
                return value;
        }
    }
    return 0;
}
function evaluateCardScore(cards) {
    for (let value = 2; value <= 14; value++)
        SCORE_RANK_COUNTS[value] = 0;
    for (let suit = 0; suit < 4; suit++) {
        SCORE_SUIT_COUNTS[suit] = 0;
        SCORE_SUIT_MASKS[suit] = 0;
    }
    const rankCounts = SCORE_RANK_COUNTS;
    const suitCounts = SCORE_SUIT_COUNTS;
    const suitMasks = SCORE_SUIT_MASKS;
    let rankMask = 0;
    for (let i = 0; i < cards.length; i++) {
        const card = cards[i];
        const value = cardService_1.RANK_VALUE[card.rank];
        const suit = SUIT_INDEX[card.suit];
        const rankBit = 1 << value;
        rankCounts[value]++;
        suitCounts[suit]++;
        suitMasks[suit] |= rankBit;
        rankMask |= rankBit;
    }
    for (let suit = 0; suit < 4; suit++) {
        if (suitCounts[suit] >= 5) {
            const straightFlushHigh = straightHighFromMask(suitMasks[suit]);
            if (straightFlushHigh)
                return makeScore(8, straightFlushHigh);
        }
    }
    for (let fourRank = 14; fourRank >= 2; fourRank--) {
        if (rankCounts[fourRank] === 4) {
            return makeScore(7, fourRank, nthHighestRank(rankMask, 1, fourRank));
        }
    }
    let bestTrips = 0;
    let secondTrips = 0;
    let bestPair = 0;
    for (let value = 14; value >= 2; value--) {
        const count = rankCounts[value];
        if (count >= 3) {
            if (!bestTrips)
                bestTrips = value;
            else if (!secondTrips)
                secondTrips = value;
        }
        else if (count >= 2 && !bestPair) {
            bestPair = value;
        }
    }
    if (bestTrips && (bestPair || secondTrips)) {
        return makeScore(6, bestTrips, bestPair || secondTrips);
    }
    for (let suit = 0; suit < 4; suit++) {
        if (suitCounts[suit] >= 5) {
            return makeScore(5, nthHighestRank(suitMasks[suit], 1), nthHighestRank(suitMasks[suit], 2), nthHighestRank(suitMasks[suit], 3), nthHighestRank(suitMasks[suit], 4), nthHighestRank(suitMasks[suit], 5));
        }
    }
    const straightHigh = straightHighFromMask(rankMask);
    if (straightHigh)
        return makeScore(4, straightHigh);
    if (bestTrips) {
        return makeScore(3, bestTrips, nthHighestRank(rankMask, 1, bestTrips), nthHighestRank(rankMask, 2, bestTrips));
    }
    let highPair = 0;
    let lowPair = 0;
    for (let value = 14; value >= 2; value--) {
        if (rankCounts[value] >= 2) {
            if (!highPair)
                highPair = value;
            else if (!lowPair) {
                lowPair = value;
                break;
            }
        }
    }
    if (highPair && lowPair) {
        return makeScore(2, highPair, lowPair, nthHighestRank(rankMask, 1, highPair, lowPair));
    }
    if (highPair) {
        return makeScore(1, highPair, nthHighestRank(rankMask, 1, highPair), nthHighestRank(rankMask, 2, highPair), nthHighestRank(rankMask, 3, highPair));
    }
    return makeScore(0, nthHighestRank(rankMask, 1), nthHighestRank(rankMask, 2), nthHighestRank(rankMask, 3), nthHighestRank(rankMask, 4), nthHighestRank(rankMask, 5));
}
function scoreHandResult(hand) {
    return makeScore(hand.rank, hand.values[0] ?? 0, hand.values[1] ?? 0, hand.values[2] ?? 0, hand.values[3] ?? 0, hand.values[4] ?? 0);
}
function dealerQualifiesScore(dealerScore) {
    const rank = scoreRank(dealerScore);
    if (rank >= 2)
        return true;
    if (rank === 1)
        return scoreFirstValue(dealerScore) >= cardService_1.RANK_VALUE['4'];
    return false;
}
function playEvFromScores(playerScore, dealerScore) {
    const anteMultiplier = getAntePayout(scoreRank(playerScore));
    if (!dealerQualifiesScore(dealerScore))
        return anteMultiplier;
    if (playerScore > dealerScore)
        return anteMultiplier + 2;
    if (playerScore < dealerScore)
        return -3;
    return 0;
}
function evaluateSeven(cards) {
    const rankCounts = new Array(15).fill(0);
    const suitCounts = [0, 0, 0, 0];
    const suitMasks = [0, 0, 0, 0];
    const rankCards = Array.from({ length: 15 }, () => []);
    let rankMask = 0;
    for (let i = 0; i < 7; i++) {
        const card = cards[i];
        const value = cardService_1.RANK_VALUE[card.rank];
        const suit = SUIT_INDEX[card.suit];
        const rankBit = 1 << value;
        rankCounts[value]++;
        suitCounts[suit]++;
        suitMasks[suit] |= rankBit;
        rankMask |= rankBit;
        rankCards[value].push(card);
    }
    for (let suit = 0; suit < 4; suit++) {
        if (suitCounts[suit] >= 5) {
            const straightFlushHigh = straightHighFromMask(suitMasks[suit]);
            if (straightFlushHigh) {
                const flushStraightCards = cards.filter((card) => SUIT_INDEX[card.suit] === suit);
                return makeResult(8, [straightFlushHigh], pickStraightCards(flushStraightCards, straightFlushHigh));
            }
        }
    }
    for (let fourRank = 14; fourRank >= 2; fourRank--) {
        if (rankCounts[fourRank] === 4) {
            const values = [fourRank];
            addHighestRanks(values, rankMask, 2, fourRank);
            return makeResult(7, values, pickCardsForRepeatedRanks(rankCards, [{ rank: fourRank, count: 4 }], [values[1]]));
        }
    }
    let bestTrips = 0;
    let secondTrips = 0;
    let bestPair = 0;
    for (let value = 14; value >= 2; value--) {
        const count = rankCounts[value];
        if (count >= 3) {
            if (!bestTrips)
                bestTrips = value;
            else if (!secondTrips)
                secondTrips = value;
        }
        else if (count >= 2 && !bestPair) {
            bestPair = value;
        }
    }
    if (bestTrips && (bestPair || secondTrips)) {
        const pairRank = bestPair || secondTrips;
        return makeResult(6, [bestTrips, pairRank], pickCardsForRepeatedRanks(rankCards, [
            { rank: bestTrips, count: 3 },
            { rank: pairRank, count: 2 },
        ]));
    }
    for (let suit = 0; suit < 4; suit++) {
        if (suitCounts[suit] >= 5) {
            const values = [];
            addHighestRanks(values, suitMasks[suit], 5);
            const flushCards = [];
            for (let i = 0; i < cards.length; i++) {
                if (SUIT_INDEX[cards[i].suit] === suit && values.includes(cardService_1.RANK_VALUE[cards[i].rank])) {
                    flushCards.push(cards[i]);
                }
            }
            flushCards.sort((a, b) => cardValue(b) - cardValue(a));
            return makeResult(5, values, flushCards.slice(0, 5));
        }
    }
    const straightHigh = straightHighFromMask(rankMask);
    if (straightHigh) {
        return makeResult(4, [straightHigh], pickStraightCards(cards, straightHigh));
    }
    if (bestTrips) {
        const values = [bestTrips];
        addHighestRanks(values, rankMask, 3, bestTrips);
        return makeResult(3, values, pickCardsForRepeatedRanks(rankCards, [{ rank: bestTrips, count: 3 }], [values[1], values[2]]));
    }
    let highPair = 0;
    let lowPair = 0;
    for (let value = 14; value >= 2; value--) {
        if (rankCounts[value] >= 2) {
            if (!highPair)
                highPair = value;
            else if (!lowPair) {
                lowPair = value;
                break;
            }
        }
    }
    if (highPair && lowPair) {
        const values = [highPair, lowPair];
        addHighestRanks(values, rankMask, 3, highPair, lowPair);
        return makeResult(2, values, pickCardsForRepeatedRanks(rankCards, [
            { rank: highPair, count: 2 },
            { rank: lowPair, count: 2 },
        ], [values[2]]));
    }
    if (highPair) {
        const values = [highPair];
        addHighestRanks(values, rankMask, 4, highPair);
        return makeResult(1, values, pickCardsForRepeatedRanks(rankCards, [{ rank: highPair, count: 2 }], [values[1], values[2], values[3]]));
    }
    const values = [];
    addHighestRanks(values, rankMask, 5);
    return makeResult(0, values, pickCardsByRank(rankCards, values));
}
const FULL_DECK = (0, cardService_1.createDeck)();
const PRO_HINT_RULES_VERSION = 'pro-exact-v1';
const proHintResultCache = new Map();
function sortedCardIds(cards) {
    return cards.map((card) => card.id).sort().join(',');
}
function getProHintCacheKey(playerCards, communityCards) {
    return [
        PRO_HINT_RULES_VERSION,
        `street:${communityCards.length}`,
        `player:${sortedCardIds(playerCards)}`,
        `community:${sortedCardIds(communityCards)}`,
    ].join('|');
}
function getProHint(playerCards, flopCards) {
    const cacheKey = getProHintCacheKey(playerCards, flopCards);
    const cached = proHintResultCache.get(cacheKey);
    if (cached)
        return cached;
    const evFold = -1;
    const knownCards = [...playerCards, ...flopCards];
    const baseRemaining = remainingDeck(knownCards);
    let totalEv = 0;
    let simulations = 0;
    let straight = 0;
    let flush = 0;
    let fullHouse = 0;
    let fourOfAKind = 0;
    let straightFlush = 0;
    let royalFlush = 0;
    let totalTurnRiverBoards = 0;
    let profitOutcomes = 0;
    let pushOutcomes = 0;
    let lossOutcomes = 0;
    const board = [flopCards[0], flopCards[1], flopCards[2], flopCards[0], flopCards[1]];
    const playerSeven = [playerCards[0], playerCards[1], board[0], board[1], board[2], board[3], board[4]];
    const dealerSeven = [board[0], board[1], board[2], board[3], board[4], board[0], board[1]];
    for (let turnIndex = 0; turnIndex < baseRemaining.length - 1; turnIndex++) {
        const turn = baseRemaining[turnIndex];
        for (let riverIndex = turnIndex + 1; riverIndex < baseRemaining.length; riverIndex++) {
            const river = baseRemaining[riverIndex];
            board[3] = turn;
            board[4] = river;
            playerSeven[5] = turn;
            playerSeven[6] = river;
            dealerSeven[2] = board[0];
            dealerSeven[3] = board[1];
            dealerSeven[4] = board[2];
            dealerSeven[5] = turn;
            dealerSeven[6] = river;
            const finalPlayerScore = evaluateCardScore(playerSeven);
            const finalPlayerRank = scoreRank(finalPlayerScore);
            totalTurnRiverBoards++;
            if (finalPlayerRank === 4 || finalPlayerRank === 8)
                straight++;
            if (finalPlayerRank === 5 || finalPlayerRank === 8)
                flush++;
            if (finalPlayerRank === 6)
                fullHouse++;
            if (finalPlayerRank === 7)
                fourOfAKind++;
            if (finalPlayerRank === 8) {
                straightFlush++;
                if (scoreFirstValue(finalPlayerScore) === 14)
                    royalFlush++;
            }
            for (let dealerOneIndex = 0; dealerOneIndex < baseRemaining.length - 1; dealerOneIndex++) {
                const dealerCardOne = baseRemaining[dealerOneIndex];
                if (dealerCardOne === turn || dealerCardOne === river)
                    continue;
                for (let dealerTwoIndex = dealerOneIndex + 1; dealerTwoIndex < baseRemaining.length; dealerTwoIndex++) {
                    const dealerCardTwo = baseRemaining[dealerTwoIndex];
                    if (dealerCardTwo === turn || dealerCardTwo === river)
                        continue;
                    dealerSeven[0] = dealerCardOne;
                    dealerSeven[1] = dealerCardTwo;
                    const dealerScore = evaluateCardScore(dealerSeven);
                    const netResult = playEvFromScores(finalPlayerScore, dealerScore);
                    totalEv += netResult;
                    if (netResult > 0)
                        profitOutcomes++;
                    else if (netResult === 0)
                        pushOutcomes++;
                    else
                        lossOutcomes++;
                    simulations++;
                }
            }
        }
    }
    const evPlay = simulations > 0 ? totalEv / simulations : -1;
    const profitOutcomePctRaw = simulations > 0 ? (profitOutcomes / simulations) * 100 : 0;
    const pushOutcomePctRaw = simulations > 0 ? (pushOutcomes / simulations) * 100 : 0;
    const lossOutcomePctRaw = simulations > 0 ? (lossOutcomes / simulations) * 100 : 0;
    const action = evPlay > evFold ? 'play' : 'fold';
    const result = {
        action,
        reason: action === 'play' ? 'Играть выгоднее по математическому ожиданию.' : 'Пас выгоднее по математическому ожиданию.',
        evPlay: Number(evPlay.toFixed(2)),
        evFold,
        straightToRiverPct: Math.round((straight / totalTurnRiverBoards) * 100),
        flushToRiverPct: Math.round((flush / totalTurnRiverBoards) * 100),
        fullHouseToRiverPct: Math.round((fullHouse / totalTurnRiverBoards) * 100),
        fourOfAKindToRiverPct: Math.round((fourOfAKind / totalTurnRiverBoards) * 100),
        straightFlushToRiverPct: Math.round((straightFlush / totalTurnRiverBoards) * 100),
        royalFlushToRiverPct: Math.round((royalFlush / totalTurnRiverBoards) * 100),
        straightToRiverPctRaw: (straight / totalTurnRiverBoards) * 100,
        flushToRiverPctRaw: (flush / totalTurnRiverBoards) * 100,
        fullHouseToRiverPctRaw: (fullHouse / totalTurnRiverBoards) * 100,
        fourOfAKindToRiverPctRaw: (fourOfAKind / totalTurnRiverBoards) * 100,
        straightFlushToRiverPctRaw: (straightFlush / totalTurnRiverBoards) * 100,
        royalFlushToRiverPctRaw: (royalFlush / totalTurnRiverBoards) * 100,
        profitOutcomePct: Math.round(profitOutcomePctRaw),
        pushOutcomePct: Math.round(pushOutcomePctRaw),
        lossOutcomePct: Math.round(lossOutcomePctRaw),
        profitOutcomePctRaw,
        pushOutcomePctRaw,
        lossOutcomePctRaw,
    };
    proHintResultCache.set(cacheKey, result);
    return result;
}
function cardValue(card) {
    return cardService_1.RANK_VALUE[card.rank];
}
function evaluateFive(cards) {
    const sorted = [...cards].sort((a, b) => cardValue(b) - cardValue(a));
    const valuesDesc = sorted.map(cardValue);
    const isFlush = cards.every((c) => c.suit === cards[0].suit);
    const uniqueValues = Array.from(new Set(valuesDesc)).sort((a, b) => b - a);
    const straightHigh = getStraightHigh(uniqueValues);
    const groups = new Map();
    for (const card of sorted) {
        const value = cardValue(card);
        const existing = groups.get(value) ?? [];
        existing.push(card);
        groups.set(value, existing);
    }
    const groupList = Array.from(groups.entries())
        .map(([value, groupCards]) => ({ value, cards: groupCards, count: groupCards.length }))
        .sort((a, b) => b.count - a.count || b.value - a.value);
    if (isFlush && straightHigh) {
        return makeResult(8, [straightHigh], pickStraightCards(cards, straightHigh));
    }
    const four = groupList.find((g) => g.count === 4);
    if (four) {
        const kicker = groupList.find((g) => g.value !== four.value);
        return makeResult(7, [four.value, kicker.value], [...four.cards, kicker.cards[0]]);
    }
    const threeGroups = groupList.filter((g) => g.count === 3).sort((a, b) => b.value - a.value);
    const pairGroups = groupList.filter((g) => g.count === 2).sort((a, b) => b.value - a.value);
    if (threeGroups.length > 0 && (pairGroups.length > 0 || threeGroups.length > 1)) {
        const trips = threeGroups[0];
        const pair = pairGroups[0] ?? threeGroups[1];
        return makeResult(6, [trips.value, pair.value], [...trips.cards, ...pair.cards.slice(0, 2)]);
    }
    if (isFlush) {
        return makeResult(5, valuesDesc, sorted.slice(0, 5));
    }
    if (straightHigh) {
        return makeResult(4, [straightHigh], pickStraightCards(cards, straightHigh));
    }
    if (threeGroups.length > 0) {
        const trips = threeGroups[0];
        const kickers = groupList
            .filter((g) => g.value !== trips.value)
            .flatMap((g) => g.cards)
            .sort((a, b) => cardValue(b) - cardValue(a))
            .slice(0, 2);
        return makeResult(3, [trips.value, ...kickers.map(cardValue)], [...trips.cards, ...kickers]);
    }
    if (pairGroups.length >= 2) {
        const highPair = pairGroups[0];
        const lowPair = pairGroups[1];
        const kicker = groupList
            .filter((g) => g.value !== highPair.value && g.value !== lowPair.value)
            .flatMap((g) => g.cards)
            .sort((a, b) => cardValue(b) - cardValue(a))[0];
        return makeResult(2, [highPair.value, lowPair.value, cardValue(kicker)], [
            ...highPair.cards,
            ...lowPair.cards,
            kicker,
        ]);
    }
    if (pairGroups.length === 1) {
        const pair = pairGroups[0];
        const kickers = groupList
            .filter((g) => g.value !== pair.value)
            .flatMap((g) => g.cards)
            .sort((a, b) => cardValue(b) - cardValue(a))
            .slice(0, 3);
        return makeResult(1, [pair.value, ...kickers.map(cardValue)], [...pair.cards, ...kickers]);
    }
    return makeResult(0, valuesDesc, sorted.slice(0, 5));
}
function makeResult(rank, values, bestCards) {
    const name = HAND_NAMES[rank];
    return {
        rank,
        name: name.en,
        nameRu: name.ru,
        values,
        bestCards,
    };
}
function getStraightHigh(valuesDesc) {
    const values = [...valuesDesc];
    if (values.includes(14))
        values.push(1);
    const sorted = Array.from(new Set(values)).sort((a, b) => b - a);
    for (let i = 0; i <= sorted.length - 5; i++) {
        const slice = sorted.slice(i, i + 5);
        if (slice.every((v, idx) => idx === 0 || v === slice[idx - 1] - 1)) {
            return slice[0] === 1 ? 5 : slice[0];
        }
    }
    return null;
}
function pickStraightCards(cards, high) {
    const needed = high === 5 ? [5, 4, 3, 2, 14] : [high, high - 1, high - 2, high - 3, high - 4];
    const picked = [];
    for (const value of needed) {
        const card = cards.find((c) => cardValue(c) === value && !picked.includes(c));
        if (card)
            picked.push(card);
    }
    return picked;
}
function evaluateBestHand(cards) {
    if (cards.length < 5) {
        return evaluateFive(cards.concat((0, cardService_1.createDeck)().slice(0, 5 - cards.length)));
    }
    if (cards.length === 5) {
        return evaluateFive(cards);
    }
    if (cards.length === 7) {
        return evaluateSeven(cards);
    }
    let best = null;
    for (const combo of combinations(cards, 5)) {
        const evaluated = evaluateFive(combo);
        if (!best || compareHands(evaluated, best) > 0) {
            best = evaluated;
        }
    }
    return best;
}
function compareHands(a, b) {
    if (a.rank !== b.rank)
        return a.rank - b.rank;
    const max = Math.max(a.values.length, b.values.length);
    for (let i = 0; i < max; i++) {
        const av = a.values[i] ?? 0;
        const bv = b.values[i] ?? 0;
        if (av !== bv)
            return av - bv;
    }
    return 0;
}
function dealerQualifies(dealerHand) {
    if (dealerHand.rank >= 2)
        return true;
    if (dealerHand.rank === 1)
        return (dealerHand.values[0] ?? 0) >= cardService_1.RANK_VALUE['4'];
    return false;
}
function getAntePayout(rank) {
    switch (rank) {
        case 8:
            return 20;
        case 7:
            return 10;
        case 6:
            return 3;
        case 5:
            return 2;
        default:
            return 1;
    }
}
function remainingDeck(knownCards) {
    const knownIds = new Set(knownCards.map((c) => c.id));
    return FULL_DECK.filter((card) => !knownIds.has(card.id));
}
function playEv(playerCards, dealerCards, communityCards) {
    const playerHand = evaluateBestHand([...playerCards, ...communityCards]);
    const dealerHand = evaluateBestHand([...dealerCards, ...communityCards]);
    return playEvFromHands(playerHand, dealerHand);
}
function playEvFromHands(playerHand, dealerHand) {
    const dQualifies = dealerQualifies(dealerHand);
    const comparison = compareHands(playerHand, dealerHand);
    const anteMultiplier = getAntePayout(playerHand.rank);
    if (!dQualifies)
        return anteMultiplier;
    if (comparison > 0)
        return anteMultiplier + 2;
    if (comparison < 0)
        return -3;
    return 0;
}

},
"./russianPoker":function(require,module,exports){
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.prepareRussianPokerDealerGamePurchase = prepareRussianPokerDealerGamePurchase;
exports.buyRussianPokerDealerGame = buyRussianPokerDealerGame;
exports.getRussianMadeCombinationCards = getRussianMadeCombinationCards;
exports.getRussianMadeCombinationIdentity = getRussianMadeCombinationIdentity;
exports.getRussianPokerSecondCombination = getRussianPokerSecondCombination;
exports.canInsureRussianPokerHand = canInsureRussianPokerHand;
exports.getRussianPokerInsuranceLimit = getRussianPokerInsuranceLimit;
exports.settleRussianPokerInsurance = settleRussianPokerInsurance;
exports.combineRussianPokerChipsDelta = combineRussianPokerChipsDelta;
exports.getRussianPokerSelectableInsuranceMaximum = getRussianPokerSelectableInsuranceMaximum;
exports.getRussianPokerPayableCombinations = getRussianPokerPayableCombinations;
exports.hasNewRussianSignificantCard = hasNewRussianSignificantCard;
exports.russianPokerDealerQualifies = russianPokerDealerQualifies;
exports.getRussianPokerBetPayout = getRussianPokerBetPayout;
exports.getRussianPokerNetSettlement = getRussianPokerNetSettlement;
exports.settleRussianPokerHand = settleRussianPokerHand;
const cardService_1 = require("./cardService");
const handEvaluator_1 = require("./handEvaluator");
/** Validates and prepares one purchase without mutating balance or settlement state. */
function prepareRussianPokerDealerGamePurchase(dealerCards, undealtCards, balance, ante, decisionAlreadyHandled = false) {
    if (decisionAlreadyHandled || ante < 0 || balance < ante)
        return null;
    return {
        replacement: buyRussianPokerDealerGame(dealerCards, undealtCards),
        purchaseCost: ante,
        balanceAfterPurchase: balance - ante,
    };
}
/** Applies the Casino Sochi dealer-game replacement to an existing physical deck. */
function buyRussianPokerDealerGame(dealerCards, undealtCards) {
    if (dealerCards.length !== 5 || undealtCards.length < 1) {
        throw new Error('Dealer-game purchase requires five dealer cards and an undealt card');
    }
    let replacedIndex = 0;
    for (let index = 1; index < dealerCards.length; index += 1) {
        if (cardService_1.RANK_VALUE[dealerCards[index].rank] > cardService_1.RANK_VALUE[dealerCards[replacedIndex].rank]) {
            replacedIndex = index;
        }
    }
    const removedCard = dealerCards[replacedIndex];
    const nextDealerCards = [...dealerCards];
    nextDealerCards[replacedIndex] = undealtCards[0];
    const firstQualified = russianPokerDealerQualifies((0, handEvaluator_1.evaluateBestHand)(nextDealerCards));
    const shouldRepeat = !firstQualified
        && undealtCards[0].rank === removedCard.rank
        && undealtCards.length > 1;
    if (shouldRepeat)
        nextDealerCards[replacedIndex] = undealtCards[1];
    return {
        dealerCards: nextDealerCards,
        removedCard,
        replacementCards: undealtCards.slice(0, shouldRepeat ? 2 : 1),
        replacedIndex,
        repeatedReplacement: shouldRepeat,
        consumedCards: shouldRepeat ? 2 : 1,
    };
}
function fiveCardSubsets(cards) {
    return cards.map((_, omittedIndex) => cards.filter((__, index) => index !== omittedIndex));
}
function getRussianMadeCombinationCards(hand) {
    if (hand.rank === 0) {
        if ((hand.values[0] ?? 0) !== cardService_1.RANK_VALUE.A || (hand.values[1] ?? 0) !== cardService_1.RANK_VALUE.K)
            return [];
        return hand.bestCards.filter((card) => card.rank === 'A' || card.rank === 'K');
    }
    switch (hand.rank) {
        case 7:
        case 3:
        case 1:
            return hand.bestCards.filter((card) => cardService_1.RANK_VALUE[card.rank] === hand.values[0]);
        case 2:
            return hand.bestCards.filter((card) => {
                const value = cardService_1.RANK_VALUE[card.rank];
                return value === hand.values[0] || value === hand.values[1];
            });
        default:
            return hand.bestCards;
    }
}
function getRussianMadeCombinationIdentity(hand) {
    return `${hand.rank}:${getRussianMadeCombinationCards(hand).map((card) => card.id).sort().join(',')}`;
}
function isPayableRussianCombination(hand) {
    return hand.rank >= 1;
}
function getRussianPokerCombinationCandidates(cards) {
    if (cards.length !== 6)
        return [];
    const byIdentity = new Map();
    for (const subset of fiveCardSubsets(cards)) {
        const hand = (0, handEvaluator_1.evaluateBestHand)(subset);
        if (!isPayableRussianCombination(hand))
            continue;
        const identity = getRussianMadeCombinationIdentity(hand);
        const existing = byIdentity.get(identity);
        if (!existing || (0, handEvaluator_1.compareHands)(hand, existing) > 0)
            byIdentity.set(identity, hand);
    }
    return [...byIdentity.values()].sort((a, b) => (0, handEvaluator_1.compareHands)(b, a));
}
/** The one optional extra payout used by both settlement and insurance limits. */
function getRussianPokerSecondCombination(cards, playerHand = (0, handEvaluator_1.evaluateBestHand)(cards), allowNormalCombination = cards.length === 6) {
    const primaryMadeCardIds = new Set(getRussianMadeCombinationCards(playerHand).map((card) => card.id));
    const secondHand = allowNormalCombination ? getRussianPokerCombinationCandidates(cards).find((hand) => hasNewRussianSignificantCard(hand, primaryMadeCardIds)) : undefined;
    if (secondHand)
        return { kind: 'hand', hand: secondHand, cards: getRussianMadeCombinationCards(secondHand), payoutMultiplier: getRussianPokerBetPayout(secondHand) };
    const aceKingCards = cards.filter((card) => card.rank === 'A' || card.rank === 'K');
    const hasAceKing = aceKingCards.some((card) => card.rank === 'A') && aceKingCards.some((card) => card.rank === 'K');
    const primaryIsAceKingHigh = playerHand.rank === 0 && (playerHand.values[0] ?? 0) === cardService_1.RANK_VALUE.A && (playerHand.values[1] ?? 0) === cardService_1.RANK_VALUE.K;
    return hasAceKing && !primaryIsAceKingHigh && aceKingCards.some((card) => !primaryMadeCardIds.has(card.id))
        ? { kind: 'ace_king', cards: aceKingCards, payoutMultiplier: 1 }
        : undefined;
}
function canInsureRussianPokerHand(cards) {
    return (0, handEvaluator_1.evaluateBestHand)(cards).rank >= 3;
}
/** Returns profit only (not the returned BET stake) and the table insurance cap. */
function getRussianPokerInsuranceLimit(cards, bet, allowSecondCombination = cards.length === 6) {
    const hand = (0, handEvaluator_1.evaluateBestHand)(cards);
    const second = getRussianPokerSecondCombination(cards, hand, allowSecondCombination);
    const potentialBetProfit = bet * (getRussianPokerBetPayout(hand) + (second?.payoutMultiplier ?? 0));
    return { potentialBetProfit, maximumInsurance: Math.floor(potentialBetProfit / 2), secondCombination: second };
}
function settleRussianPokerInsurance(insuranceBet, originalDealerCards, playerCards) {
    if (insuranceBet <= 0)
        return { result: 'returned', chipsReturned: 0, profit: 0 };
    const dealerHand = (0, handEvaluator_1.evaluateBestHand)(originalDealerCards);
    if (!russianPokerDealerQualifies(dealerHand))
        return { result: 'won', chipsReturned: insuranceBet * 2, profit: insuranceBet };
    if ((0, handEvaluator_1.compareHands)((0, handEvaluator_1.evaluateBestHand)(playerCards), dealerHand) > 0)
        return { result: 'lost', chipsReturned: 0, profit: -insuranceBet };
    return { result: 'returned', chipsReturned: insuranceBet, profit: 0 };
}
function combineRussianPokerChipsDelta(mainHandChipsDelta, insuranceBet, insuranceChipsReturned) {
    return mainHandChipsDelta - insuranceBet + insuranceChipsReturned;
}
/** Caps an insurance amount to spendable whole-ANTE increments. */
function getRussianPokerSelectableInsuranceMaximum(ruleMaximum, availableBalance, ante) {
    if (ante <= 0 || ruleMaximum <= 0 || availableBalance <= 0)
        return 0;
    return Math.floor(Math.min(ruleMaximum, availableBalance) / ante) * ante;
}
/** Returns at most the two strongest distinct made combinations in a six-card hand. */
function getRussianPokerPayableCombinations(cards) {
    return getRussianPokerCombinationCandidates(cards).slice(0, 2);
}
function hasNewRussianSignificantCard(hand, primaryMadeCardIds) {
    return getRussianMadeCombinationCards(hand).some((card) => !primaryMadeCardIds.has(card.id));
}
function russianPokerDealerQualifies(dealerHand) {
    if (dealerHand.rank >= 1)
        return true;
    return (dealerHand.values[0] ?? 0) === cardService_1.RANK_VALUE.A && (dealerHand.values[1] ?? 0) >= cardService_1.RANK_VALUE.K;
}
function getRussianPokerBetPayout(hand) {
    if (hand.rank === 8 && (hand.values[0] ?? 0) === cardService_1.RANK_VALUE.A)
        return 100;
    switch (hand.rank) {
        case 8:
            return 50;
        case 7:
            return 20;
        case 6:
            return 7;
        case 5:
            return 5;
        case 4:
            return 4;
        case 3:
            return 3;
        case 2:
            return 2;
        case 1:
            return 1;
        default:
            return 1;
    }
}
/** Shared net-settlement primitive for callers that precompute hand comparisons. */
function getRussianPokerNetSettlement(dealerQualified, comparison, ante, bet, alreadyPaidCosts, payout, secondPayout = 0, purchasedDealerGame = false) {
    let chipsGained;
    if (!dealerQualified)
        chipsGained = purchasedDealerGame ? ante + bet : ante * 2 + bet;
    else if (comparison > 0)
        chipsGained = ante + bet + bet * (payout + secondPayout);
    else if (comparison < 0)
        chipsGained = 0;
    else
        chipsGained = ante + bet;
    return chipsGained - ante - bet - alreadyPaidCosts;
}
function settleRussianPokerHand(playerCards, dealerCards, ante, bet, alreadyPaidCosts = 0, allowSecondCombination = false, purchasedDealerGame = false) {
    const playerHand = (0, handEvaluator_1.evaluateBestHand)(playerCards);
    const dealerHand = (0, handEvaluator_1.evaluateBestHand)(dealerCards);
    const dealerQualified = russianPokerDealerQualifies(dealerHand);
    const comparison = (0, handEvaluator_1.compareHands)(playerHand, dealerHand);
    const payout = getRussianPokerBetPayout(playerHand);
    const secondCombination = getRussianPokerSecondCombination(playerCards, playerHand, allowSecondCombination);
    const secondHand = secondCombination?.kind === 'hand' ? secondCombination.hand : undefined;
    const secondPayout = secondCombination?.payoutMultiplier;
    let chipsGained = 0;
    let outcome = 'push';
    let anteResultKey = 'russianAnteReturns';
    let betResultKey = 'russianBetReturns';
    if (!dealerQualified) {
        chipsGained = purchasedDealerGame ? ante + bet : ante * 2 + bet;
        outcome = purchasedDealerGame ? 'push' : 'player_wins';
        anteResultKey = purchasedDealerGame ? 'russianAnteReturns' : 'russianAntePays';
        betResultKey = 'russianBetReturns';
    }
    else if (comparison > 0) {
        chipsGained = ante + bet + bet * (payout + (secondPayout ?? 0));
        outcome = 'player_wins';
        anteResultKey = 'russianAnteReturns';
        betResultKey = 'russianBetPaysByTable';
    }
    else if (comparison < 0) {
        chipsGained = 0;
        outcome = 'dealer_wins';
        anteResultKey = 'russianAnteLost';
        betResultKey = 'russianBetLost';
    }
    else {
        chipsGained = ante + bet;
        outcome = 'push';
        anteResultKey = 'russianAnteReturns';
        betResultKey = 'russianBetReturns';
    }
    const sharedChipsDelta = getRussianPokerNetSettlement(dealerQualified, comparison, ante, bet, alreadyPaidCosts, payout, secondPayout, purchasedDealerGame);
    return {
        playerHand,
        dealerHand,
        dealerQualified,
        outcome,
        chipsGained,
        chipsDelta: sharedChipsDelta,
        anteResultKey,
        betResultKey,
        betPayoutMultiplier: betResultKey === 'russianBetPaysByTable' ? payout : undefined,
        secondHand: betResultKey === 'russianBetPaysByTable' ? secondHand : undefined,
        secondBetPayoutMultiplier: betResultKey === 'russianBetPaysByTable' ? secondPayout : undefined,
        secondCombination: betResultKey === 'russianBetPaysByTable' ? secondCombination : undefined,
        anteMultiplier: dealerQualified || purchasedDealerGame ? 0 : 1,
    };
}

},
"./russianPokerHint":function(require,module,exports){
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.RUSSIAN_POKER_HINT_RULES_VERSION = void 0;
exports.getRussianPokerHintCacheKey = getRussianPokerHintCacheKey;
exports.getRussianPokerDeterministicSample = getRussianPokerDeterministicSample;
exports.getRussianPokerRevealedDealerPurchaseEv = getRussianPokerRevealedDealerPurchaseEv;
exports.getRussianPokerFinalHint = getRussianPokerFinalHint;
exports.getRussianPokerInsuranceHint = getRussianPokerInsuranceHint;
exports.getRussianPokerDealerGameHint = getRussianPokerDealerGameHint;
exports.getRussianPokerInitialHint = getRussianPokerInitialHint;
exports.clearRussianPokerHintCache = clearRussianPokerHintCache;
const cardService_1 = require("./cardService");
const handEvaluator_1 = require("./handEvaluator");
const russianPoker_1 = require("./russianPoker");
exports.RUSSIAN_POKER_HINT_RULES_VERSION = 'russian-poker-sochi-v2';
/** Multi-card candidates use 256 screening deals and at most 768 high-precision replicas. */
const MIN_SAMPLES = 256;
const MAX_SAMPLES = 768;
const CONFIDENCE_Z = 2.58;
const COARSE_CONTINUATION_SAMPLES = 4;
const PRECISE_CONTINUATION_SAMPLES = 24;
const EXACT_OUTER_CONTINUATION_SAMPLES = 96;
const COARSE_PURCHASE_SAMPLES = 4;
const PRECISE_PURCHASE_SAMPLES = 8;
const resultCache = new Map();
const sortedIds = (cards = []) => cards.map((card) => card.id).sort();
const ratio = (amount, ante) => Number((amount / ante).toFixed(8));
function getRussianPokerHintCacheKey(phase, state) {
    return [exports.RUSSIAN_POKER_HINT_RULES_VERSION, phase, sortedIds(state.playerCards).join(','), state.dealerVisibleCard.id,
        sortedIds(state.discardedPlayerCards).join(','), `ante:${state.ante}`, `balance:${ratio(state.availableBalance, state.ante)}`,
        Number(Boolean(state.improvementUsed)), state.improvementType ?? '-', `cost:${ratio(state.improvementCost ?? 0, state.ante)}`].join('|');
}
function samplingKey(phase, state) {
    return getRussianPokerHintCacheKey(phase, state).replace(`|ante:${state.ante}|`, '|ante:normalized|');
}
function validate(cards) {
    if (new Set(cards.map((card) => card.id)).size !== cards.length)
        throw new Error('Duplicate physical card');
}
function unknownDeck(known) {
    validate(known);
    const unavailable = new Set(known.map((card) => card.id));
    return (0, cardService_1.createDeck)().filter((card) => !unavailable.has(card.id));
}
function hash(value) {
    let result = 2166136261;
    for (let index = 0; index < value.length; index += 1) {
        result ^= value.charCodeAt(index);
        result = Math.imul(result, 16777619);
    }
    return result >>> 0;
}
function seeded(seed) {
    let state = seed || 0x9e3779b9;
    return () => {
        state += 0x6d2b79f5;
        let value = state;
        value = Math.imul(value ^ value >>> 15, value | 1);
        value ^= value + Math.imul(value ^ value >>> 7, value | 61);
        return ((value ^ value >>> 14) >>> 0) / 4294967296;
    };
}
function sampledPrefix(deck, seed, count) {
    const result = [...deck];
    const next = seeded(seed);
    for (let index = 0; index < count; index += 1) {
        const other = index + Math.floor(next() * (result.length - index));
        [result[index], result[other]] = [result[other], result[index]];
    }
    return result;
}
function getRussianPokerDeterministicSample(knownCards, seed, count) {
    if (count < 0)
        throw new Error('Sample count cannot be negative');
    const deck = unknownDeck(knownCards);
    if (count > deck.length)
        throw new Error('Sample exceeds unknown deck');
    return sampledPrefix(deck, hash(`${exports.RUSSIAN_POKER_HINT_RULES_VERSION}|${seed}`), count).slice(0, count);
}
function dealerQualifiesScore(score) { return (0, handEvaluator_1.scoreRank)(score) >= 1 || ((0, handEvaluator_1.scoreFirstValue)(score) === 14 && ((score / 15 ** 3) % 15 | 0) >= 13); }
function preparedPlayer(cards) {
    const hand = (0, handEvaluator_1.evaluateBestHand)(cards);
    const second = (0, russianPoker_1.getRussianPokerSecondCombination)(cards, hand, cards.length === 6);
    return { hand, score: (0, handEvaluator_1.scoreHandResult)(hand), payout: (0, russianPoker_1.getRussianPokerBetPayout)(hand), secondPayout: second?.payoutMultiplier ?? 0 };
}
function scenarioNet(player, dealerScore, ante, cost, purchased = false) {
    return (0, russianPoker_1.getRussianPokerNetSettlement)(dealerQualifiesScore(dealerScore), Math.sign(player.score - dealerScore), ante, ante * 2, cost, player.payout, player.secondPayout, purchased) / ante;
}
function forEachFour(deck, visit) {
    for (let a = 0; a < deck.length - 3; a += 1)
        for (let b = a + 1; b < deck.length - 2; b += 1)
            for (let c = b + 1; c < deck.length - 1; c += 1)
                for (let d = c + 1; d < deck.length; d += 1)
                    visit(deck[a], deck[b], deck[c], deck[d]);
}
function normalized(result) {
    const order = { fold: 0, play: 1, buy_sixth_card: 2, exchange: 3, no_insurance: 4, insure: 5, take_ante: 6, buy_dealer_game: 7 };
    return { ...result, candidates: result.candidates.map((candidate) => ({ ...candidate, ev: Number(candidate.ev.toFixed(8)) }))
            .sort((a, b) => order[a.action] - order[b.action] || (a.exchangeCardIds?.join(',') ?? '').localeCompare(b.exchangeCardIds?.join(',') ?? '')) };
}
/** Exact, equally weighted expectation: a repeated draw is conditional within its one first-card outcome. */
function purchaseEvPrepared(player, dealer, deck, ante, cost) {
    let replacedIndex = 0;
    for (let index = 1; index < dealer.length; index += 1)
        if (cardService_1.RANK_VALUE[dealer[index].rank] > cardService_1.RANK_VALUE[dealer[replacedIndex].rank])
            replacedIndex = index;
    const removed = dealer[replacedIndex];
    const replaced = [...dealer];
    let firstCardTotal = 0;
    for (let first = 0; first < deck.length; first += 1) {
        replaced[replacedIndex] = deck[first];
        const firstScore = (0, handEvaluator_1.evaluateCardScore)(replaced);
        let firstValue;
        if (deck[first].rank === removed.rank && !dealerQualifiesScore(firstScore)) {
            let secondTotal = 0;
            for (let second = 0; second < deck.length; second += 1)
                if (second !== first) {
                    replaced[replacedIndex] = deck[second];
                    secondTotal += scenarioNet(player, (0, handEvaluator_1.evaluateCardScore)(replaced), ante, cost + ante, true);
                }
            firstValue = secondTotal / (deck.length - 1);
        }
        else
            firstValue = scenarioNet(player, firstScore, ante, cost + ante, true);
        firstCardTotal += firstValue;
    }
    return firstCardTotal / deck.length;
}
function getRussianPokerRevealedDealerPurchaseEv(state) {
    validate([...state.playerCards, ...state.dealerCards, ...(state.discardedPlayerCards ?? [])]);
    if ((0, russianPoker_1.russianPokerDealerQualifies)((0, handEvaluator_1.evaluateBestHand)(state.dealerCards)) || !(0, russianPoker_1.russianPokerDealerQualifies)((0, handEvaluator_1.evaluateBestHand)(state.playerCards)) || state.availableBalance < state.ante)
        return Number.NEGATIVE_INFINITY;
    const deck = unknownDeck([...state.playerCards, ...state.dealerCards, ...(state.discardedPlayerCards ?? [])]);
    return purchaseEvPrepared(preparedPlayer(state.playerCards), state.dealerCards, deck, state.ante, state.improvementCost ?? 0);
}
function getRussianPokerFinalHint(state) {
    const key = getRussianPokerHintCacheKey('final_play_fold', state);
    const cached = resultCache.get(key);
    if (cached)
        return cached;
    if (state.ante <= 0)
        throw new Error('ANTE must be positive');
    const cost = state.improvementCost ?? 0;
    const foldEv = -(state.ante + cost) / state.ante;
    const candidates = [{ action: 'fold', ev: foldEv }];
    if (state.availableBalance >= state.ante * 2) {
        const known = [...state.playerCards, state.dealerVisibleCard, ...(state.discardedPlayerCards ?? [])];
        const deck = unknownDeck(known);
        const player = preparedPlayer(state.playerCards);
        const postBetBalance = state.availableBalance - state.ante * 2;
        const insuranceMaximum = (0, russianPoker_1.canInsureRussianPokerHand)(state.playerCards) ? (0, russianPoker_1.getRussianPokerSelectableInsuranceMaximum)((0, russianPoker_1.getRussianPokerInsuranceLimit)(state.playerCards, state.ante * 2, state.playerCards.length === 6).maximumInsurance, postBetBalance, state.ante) : 0;
        let baseTotal = 0;
        let noGame = 0;
        let lost = 0;
        let count = 0;
        forEachFour(deck, (a, b, c, d) => {
            const dealerScore = (0, handEvaluator_1.evaluateCardScore)([state.dealerVisibleCard, a, b, c, d]);
            baseTotal += scenarioNet(player, dealerScore, state.ante, cost);
            count += 1;
            if (!dealerQualifiesScore(dealerScore))
                noGame += 1;
            else if (player.score > dealerScore)
                lost += 1;
        });
        const insuranceBet = noGame > lost ? insuranceMaximum : 0;
        let purchaseGain = 0;
        // With only a 1:1 BET payout, even the best purchased outcome merely ties Take ANTE;
        // all other replacements are worse, so purchase cannot improve exact Play EV.
        if (player.payout + player.secondPayout > 1 && (0, russianPoker_1.russianPokerDealerQualifies)(player.hand) && postBetBalance + insuranceBet >= state.ante) {
            forEachFour(deck, (a, b, c, d) => {
                const dealer = [state.dealerVisibleCard, a, b, c, d];
                if (dealerQualifiesScore((0, handEvaluator_1.evaluateCardScore)(dealer)))
                    return;
                const remaining = deck.filter((card) => card !== a && card !== b && card !== c && card !== d);
                const buyEv = purchaseEvPrepared(player, dealer, remaining, state.ante, cost);
                const takeEv = scenarioNet(player, (0, handEvaluator_1.evaluateCardScore)(dealer), state.ante, cost);
                purchaseGain += Math.max(0, buyEv - takeEv);
            });
        }
        const insuranceGain = insuranceBet * (noGame - lost) / state.ante;
        candidates.push({ action: 'play', ev: (baseTotal + insuranceGain + purchaseGain) / count });
    }
    const play = candidates.find((candidate) => candidate.action === 'play');
    const recommendedAction = play && play.ev > foldEv ? 'play' : 'fold';
    const result = normalized({ phase: 'final_play_fold', recommendedAction, candidates, method: 'exact',
        reason: { key: play?.ev === foldEv ? 'exact_tie_lower_cost' : 'highest_expected_value' } });
    resultCache.set(key, result);
    return result;
}
function getRussianPokerInsuranceHint(state) {
    const key = getRussianPokerHintCacheKey('insurance', state);
    const cached = resultCache.get(key);
    if (cached)
        return cached;
    const deck = unknownDeck([...state.playerCards, state.dealerVisibleCard, ...(state.discardedPlayerCards ?? [])]);
    const player = preparedPlayer(state.playerCards);
    let noGame = 0;
    let lost = 0;
    let returned = 0;
    let count = 0;
    forEachFour(deck, (a, b, c, d) => {
        const score = (0, handEvaluator_1.evaluateCardScore)([state.dealerVisibleCard, a, b, c, d]);
        count += 1;
        if (!dealerQualifiesScore(score))
            noGame += 1;
        else if (player.score > score)
            lost += 1;
        else
            returned += 1;
    });
    const unitEv = (noGame - lost) / count;
    const maximum = (0, russianPoker_1.canInsureRussianPokerHand)(state.playerCards) ? (0, russianPoker_1.getRussianPokerSelectableInsuranceMaximum)((0, russianPoker_1.getRussianPokerInsuranceLimit)(state.playerCards, state.ante * 2, state.playerCards.length === 6).maximumInsurance, state.availableBalance, state.ante) : 0;
    const insure = unitEv > 0 && maximum > 0;
    const candidates = [{ action: 'no_insurance', ev: 0 }];
    if (maximum > 0)
        candidates.push({ action: 'insure', insuranceAmount: maximum, ev: unitEv * maximum / state.ante });
    const result = normalized({ phase: 'insurance', recommendedAction: insure ? 'insure' : 'no_insurance', recommendedInsuranceAmount: insure ? maximum : undefined,
        candidates, method: 'exact', reason: { key: insure ? 'positive_insurance_unit_ev' : 'non_positive_insurance_unit_ev', unitEv },
        probabilities: { dealerNoGame: noGame / count, insuranceLost: lost / count, insuranceReturned: returned / count } });
    resultCache.set(key, result);
    return result;
}
function getRussianPokerDealerGameHint(state) {
    validate([...state.playerCards, ...state.dealerCards, ...(state.discardedPlayerCards ?? [])]);
    const player = preparedPlayer(state.playerCards);
    const dealerScore = (0, handEvaluator_1.evaluateCardScore)(state.dealerCards);
    const take = scenarioNet(player, dealerScore, state.ante, state.improvementCost ?? 0);
    const candidates = [{ action: 'take_ante', ev: take }];
    const buyEv = getRussianPokerRevealedDealerPurchaseEv(state);
    if (Number.isFinite(buyEv))
        candidates.push({ action: 'buy_dealer_game', ev: buyEv });
    const recommendedAction = Number.isFinite(buyEv) && buyEv > take ? 'buy_dealer_game' : 'take_ante';
    return normalized({ phase: 'dealer_game', recommendedAction, candidates, method: 'exact',
        reason: { key: !Number.isFinite(buyEv) ? 'dealer_game_not_legal' : buyEv === take ? 'exact_tie_lower_cost' : 'highest_expected_value' } });
}
function sampledPurchaseEv(player, dealer, remaining, ante, cost, seedKey, samples) {
    const take = scenarioNet(player, (0, handEvaluator_1.evaluateCardScore)(dealer), ante, cost);
    let total = 0;
    for (let sample = 0; sample < samples; sample += 1) {
        const draw = sampledPrefix(remaining, hash(`${seedKey}|purchase|${sample}`), 2);
        const replacement = (0, russianPoker_1.buyRussianPokerDealerGame)(dealer, draw);
        total += scenarioNet(player, (0, handEvaluator_1.evaluateCardScore)(replacement.dealerCards), ante, cost + ante, true);
    }
    return Math.max(take, total / samples);
}
function purchaseDecisionAndEvaluation(player, dealer, remaining, ante, cost, key, samples) {
    const take = scenarioNet(player, (0, handEvaluator_1.evaluateCardScore)(dealer), ante, cost);
    const decisionBuy = sampledPurchaseEv(player, dealer, remaining, ante, cost, `${key}|decision`, samples) > take;
    if (!decisionBuy)
        return take;
    // Selection and scoring use disjoint deterministic replacement streams.
    let total = 0;
    for (let sample = 0; sample < samples; sample += 1) {
        const draw = sampledPrefix(remaining, hash(`${key}|evaluation|${sample}`), 2);
        const replacement = (0, russianPoker_1.buyRussianPokerDealerGame)(dealer, draw);
        total += scenarioNet(player, (0, handEvaluator_1.evaluateCardScore)(replacement.dealerCards), ante, cost + ante, true);
    }
    return total / samples;
}
/** Independent visible-state continuation replica; decision and evaluation streams are disjoint. */
function visibleContinuation(state, precision, replicaKey, sampleOverride) {
    const continuationSamples = sampleOverride ?? (precision === 'precise' ? PRECISE_CONTINUATION_SAMPLES : COARSE_CONTINUATION_SAMPLES);
    const purchaseSamples = precision === 'precise' ? PRECISE_PURCHASE_SAMPLES : COARSE_PURCHASE_SAMPLES;
    const key = `${samplingKey('final_play_fold', state)}|continuation|${precision}|replica:${replicaKey}`;
    const known = [...state.playerCards, state.dealerVisibleCard, ...(state.discardedPlayerCards ?? [])];
    const deck = unknownDeck(known);
    const player = preparedPlayer(state.playerCards);
    const cost = state.improvementCost ?? 0;
    const fold = -(state.ante + cost) / state.ante;
    const postBet = state.availableBalance - state.ante * 2;
    if (postBet < 0)
        return { ev: fold, varianceOfMean: 0 };
    const insuranceMax = (0, russianPoker_1.canInsureRussianPokerHand)(state.playerCards) ? (0, russianPoker_1.getRussianPokerSelectableInsuranceMaximum)((0, russianPoker_1.getRussianPokerInsuranceLimit)(state.playerCards, state.ante * 2, state.playerCards.length === 6).maximumInsurance, postBet, state.ante) : 0;
    const decisionScenarios = [];
    let decisionNoGame = 0;
    let decisionLost = 0;
    for (let sample = 0; sample < continuationSamples; sample += 1) {
        const draw = sampledPrefix(deck, hash(`${key}|hidden|${sample}`), 4);
        const dealer = [state.dealerVisibleCard, ...draw.slice(0, 4)];
        const score = (0, handEvaluator_1.evaluateCardScore)(dealer);
        decisionScenarios.push({ dealer, remaining: draw.slice(4), score });
        if (!dealerQualifiesScore(score))
            decisionNoGame += 1;
        else if (player.score > score)
            decisionLost += 1;
    }
    const insurance = decisionNoGame > decisionLost ? insuranceMax : 0;
    let decisionPlayTotal = 0;
    decisionScenarios.forEach((scenario, sample) => {
        let value = scenarioNet(player, scenario.score, state.ante, cost);
        if (!dealerQualifiesScore(scenario.score) && (0, russianPoker_1.russianPokerDealerQualifies)(player.hand) && postBet + insurance >= state.ante)
            value = purchaseDecisionAndEvaluation(player, scenario.dealer, scenario.remaining, state.ante, cost, `${key}|play-decision|${sample}`, purchaseSamples);
        value += insurance > 0 ? (!dealerQualifiesScore(scenario.score) ? insurance / state.ante : player.score > scenario.score ? -insurance / state.ante : 0) : 0;
        decisionPlayTotal += value;
    });
    const decisionPlays = decisionPlayTotal / continuationSamples > fold;
    if (!decisionPlays)
        return { ev: fold, varianceOfMean: 0 };
    let total = 0;
    let squares = 0;
    for (let sample = 0; sample < continuationSamples; sample += 1) {
        const draw = sampledPrefix(deck, hash(`${key}|evaluation-hidden|${sample}`), 4);
        const dealer = [state.dealerVisibleCard, ...draw.slice(0, 4)];
        const score = (0, handEvaluator_1.evaluateCardScore)(dealer);
        let value = scenarioNet(player, score, state.ante, cost);
        if (!dealerQualifiesScore(score) && (0, russianPoker_1.russianPokerDealerQualifies)(player.hand) && postBet + insurance >= state.ante)
            value = purchaseDecisionAndEvaluation(player, dealer, draw.slice(4), state.ante, cost, `${key}|dealer|${sample}`, purchaseSamples);
        value += insurance > 0 ? (!dealerQualifiesScore(score) ? insurance / state.ante : player.score > score ? -insurance / state.ante : 0) : 0;
        total += value;
        squares += value * value;
    }
    const ev = total / continuationSamples;
    const sampleVariance = continuationSamples > 1 ? Math.max(0, (squares - total * total / continuationSamples) / (continuationSamples - 1)) : 0;
    return { ev, varianceOfMean: sampleVariance / continuationSamples };
}
function initialCandidates(state) {
    const result = [{ action: 'fold' }];
    if (state.availableBalance >= state.ante * 2)
        result.push({ action: 'play' });
    if (state.availableBalance >= state.ante) {
        result.push({ action: 'buy_sixth_card' });
        for (let mask = 1; mask < 32; mask += 1)
            result.push({ action: 'exchange', exchangeCardIds: state.playerCards.filter((_, index) => mask & 1 << index).map((card) => card.id).sort() });
    }
    return result;
}
function tieOrder(candidate) { const order = { fold: 0, play: 1, buy_sixth_card: 2, exchange: 3 }; return `${order[candidate.action]}:${candidate.exchangeCardIds?.join(',') ?? ''}`; }
function getRussianPokerInitialHint(state) {
    if (state.improvementUsed)
        return getRussianPokerFinalHint(state);
    if (state.playerCards.length !== 5 || state.ante <= 0)
        throw new Error('Initial hint requires five cards and a positive ANTE');
    const key = getRussianPokerHintCacheKey('initial', state);
    const seedKey = samplingKey('initial', state);
    const cached = resultCache.get(key);
    if (cached)
        return cached;
    const candidates = initialCandidates(state);
    const deck = unknownDeck([...state.playerCards, state.dealerVisibleCard, ...(state.discardedPlayerCards ?? [])]);
    if (candidates.length === 1) {
        const result = normalized({ phase: 'initial', recommendedAction: 'fold', candidates: [{ action: 'fold', ev: -1 }],
            method: 'deterministic_monte_carlo', sampleCount: 0, reason: { key: 'only_legal_action' } });
        resultCache.set(key, result);
        return result;
    }
    const directPlayIndex = candidates.findIndex((candidate) => candidate.action === 'play');
    const exactPlayEv = directPlayIndex >= 0 ? getRussianPokerFinalHint({ ...state, improvementUsed: true }).candidates.find((candidate) => candidate.action === 'play').ev : 0;
    const outcome = (candidate, draw, precision, replicaKey, sampleOverride) => {
        let cards = state.playerCards;
        let cost = 0;
        if (candidate.action === 'buy_sixth_card') {
            cards = [...cards, draw[4]];
            cost = state.ante;
        }
        else {
            const exchanged = new Set(candidate.exchangeCardIds);
            cards = [...cards.filter((card) => !exchanged.has(card.id)), ...draw.slice(4, 4 + exchanged.size)];
            cost = state.ante;
        }
        return visibleContinuation({ ...state, playerCards: cards,
            discardedPlayerCards: [...(state.discardedPlayerCards ?? []), ...state.playerCards.filter((card) => candidate.exchangeCardIds?.includes(card.id))],
            availableBalance: state.availableBalance - cost, improvementUsed: true, improvementType: candidate.action === 'exchange' ? 'exchange' : 'sixth_card', improvementCost: cost }, precision, replicaKey, sampleOverride);
    };
    const makeStats = (precision, exactOuter) => ({ count: 0, sum: 0, squares: 0, innerVariance: 0, precision, exactOuter });
    const add = (stats, estimate) => {
        stats.count += 1;
        stats.sum += estimate.ev;
        stats.squares += estimate.ev * estimate.ev;
        stats.innerVariance += estimate.varianceOfMean;
    };
    const mean = (stats) => stats.sum / stats.count;
    const standardError = (stats) => {
        if (stats.exactOuter || stats.count < 2)
            return Math.sqrt(stats.innerVariance) / Math.max(1, stats.count);
        const outerVariance = Math.max(0, (stats.squares - stats.sum ** 2 / stats.count) / (stats.count - 1));
        return Math.sqrt(outerVariance / stats.count + stats.innerVariance / (stats.count * stats.count));
    };
    const isOneCard = (candidate) => candidate.action === 'buy_sixth_card' || candidate.exchangeCardIds?.length === 1;
    const evaluateStats = (candidate, precision, samples) => {
        const stats = makeStats(precision, isOneCard(candidate));
        if (isOneCard(candidate)) {
            // These marginals are finite: visit every legal physical replacement exactly once.
            const innerSamples = precision === 'precise' ? EXACT_OUTER_CONTINUATION_SAMPLES : undefined;
            deck.forEach((replacement) => add(stats, outcome(candidate, [replacement, replacement, replacement, replacement, replacement], precision, `card:${replacement.id}`, innerSamples)));
        }
        else {
            for (let sample = 0; sample < samples; sample += 1) {
                const draw = sampledPrefix(deck, hash(`${seedKey}|outer|${sample}`), 9);
                add(stats, outcome(candidate, draw, precision, `outer:${sample}`));
            }
        }
        return stats;
    };
    // Every action gets a confidence interval during screening; repeated states use distinct replica keys.
    const statsByIndex = new Map();
    candidates.forEach((candidate, index) => {
        if (candidate.action === 'exchange' || candidate.action === 'buy_sixth_card')
            statsByIndex.set(index, evaluateStats(candidate, 'coarse', MIN_SAMPLES));
    });
    const evAt = (index) => candidates[index].action === 'fold' ? -1 : candidates[index].action === 'play' ? exactPlayEv : mean(statsByIndex.get(index));
    const seAt = (index) => statsByIndex.has(index) ? standardError(statsByIndex.get(index)) : 0;
    const lower = (index) => evAt(index) - CONFIDENCE_Z * seAt(index);
    const upper = (index) => evAt(index) + CONFIDENCE_Z * seAt(index);
    let best = candidates.map((_, index) => index).sort((a, b) => evAt(b) - evAt(a) || tieOrder(candidates[a]).localeCompare(tieOrder(candidates[b])))[0];
    const promoted = new Set();
    candidates.forEach((candidate, index) => {
        if ((candidate.action === 'exchange' || candidate.action === 'buy_sixth_card') && (isOneCard(candidate) || upper(index) >= lower(best)))
            promoted.add(index);
    });
    // Reevaluate every overlapping action, plus every finite one-card action, using disjoint high-precision replicas.
    promoted.forEach((index) => statsByIndex.set(index, evaluateStats(candidates[index], 'precise', MAX_SAMPLES)));
    best = candidates.map((_, index) => index).sort((a, b) => evAt(b) - evAt(a) || tieOrder(candidates[a]).localeCompare(tieOrder(candidates[b])))[0];
    // Keep promoting until every action overlapping the current best has a precise interval.
    while (true) {
        best = candidates.map((_, index) => index).sort((a, b) => evAt(b) - evAt(a) || tieOrder(candidates[a]).localeCompare(tieOrder(candidates[b])))[0];
        const newlyOverlapping = candidates.map((candidate, index) => ({ candidate, index })).filter(({ candidate, index }) => (candidate.action === 'exchange' || candidate.action === 'buy_sixth_card') && statsByIndex.get(index)?.precision === 'coarse' && upper(index) >= lower(best));
        if (newlyOverlapping.length === 0)
            break;
        newlyOverlapping.forEach(({ candidate, index }) => { statsByIndex.set(index, evaluateStats(candidate, 'precise', MAX_SAMPLES)); promoted.add(index); });
    }
    const separated = candidates.every((_, index) => index === best || lower(best) > upper(index));
    const evaluated = candidates.map((candidate, index) => ({ ...candidate, ev: evAt(index), standardError: seAt(index),
        precision: candidate.action === 'fold' || candidate.action === 'play' ? 'exact'
            : statsByIndex.get(index).exactOuter && statsByIndex.get(index).precision === 'precise' ? 'exact_outer_precise_inner' : statsByIndex.get(index).precision }));
    const winner = [...evaluated].sort((a, b) => b.ev - a.ev || tieOrder(a).localeCompare(tieOrder(b)))[0];
    const result = normalized({ phase: 'initial', recommendedAction: winner.action, recommendedExchangeCardIds: winner.exchangeCardIds, candidates: evaluated,
        method: 'deterministic_monte_carlo', sampleCount: MAX_SAMPLES, reason: { key: separated ? 'statistically_separated_with_inner_uncertainty' : 'max_samples_reached',
            minimumSamples: MIN_SAMPLES, maximumSamples: MAX_SAMPLES, preciseContinuationSamples: PRECISE_CONTINUATION_SAMPLES } });
    resultCache.set(key, result);
    return result;
}
function clearRussianPokerHintCache() { resultCache.clear(); }

}},cache={};
function require(id){const key=id.replace(/\.js$/,'');if(cache[key])return cache[key].exports;const factory=modules[key];if(!factory)throw new Error('Unknown worker module '+key);const module={exports:{}};cache[key]=module;factory(require,module,module.exports);return module.exports;}
const engine=require('./russianPokerHint');
self.onmessage=({data})=>{const {id,request}=data;try{let result;switch(request.phase){case 'initial':result=engine.getRussianPokerInitialHint(request.state);break;case 'final_play_fold':result=engine.getRussianPokerFinalHint(request.state);break;case 'insurance':result=engine.getRussianPokerInsuranceHint(request.state);break;case 'dealer_game':result=engine.getRussianPokerDealerGameHint(request.state);break;default:throw new Error('Unsupported phase');}self.postMessage({id,result});}catch(error){self.postMessage({id,error:error instanceof Error?error.message:String(error)});}};
